services:
  - name: Google
    url: https://www.google.com
    type: http

  - name: GitHub
    url: https://github.com
    type: http

  - name: Local Flask App
    url: http://127.0.0.1:5000
    type: http